export const CLUB_CLUES: Record<string, { colors: string; icon: string }> = {
  "Arsenal": { colors: "red and white", icon: "a cannon" },
  "Aston Villa": { colors: "claret and blue", icon: "a lion" },
  "AFC Bournemouth": { colors: "red and black stripes", icon: "a monogram, no central emblem" },
  "Brentford": { colors: "red, white and black stripes", icon: "a bee" },
  "Brighton & Hove Albion": { colors: "blue and white stripes", icon: "a seagull" },
  "Chelsea": { colors: "royal blue", icon: "a lion holding a staff" },
  "Coventry City": { colors: "sky blue", icon: "an elephant" },
  "Crystal Palace": { colors: "red and blue", icon: "an eagle" },
  "Everton": { colors: "royal blue", icon: "a laurel wreath and a tower" },
  "Fulham": { colors: "white and black", icon: "a shield with a river motif" },
  "Hull City": { colors: "black and amber tiger stripes", icon: "a tiger" },
  "Ipswich Town": { colors: "blue", icon: "a horse" },
  "Leeds United": { colors: "white and yellow", icon: "a globe motif" },
  "Liverpool": { colors: "red", icon: "a liver bird" },
  "Manchester City": { colors: "sky blue", icon: "a ship and roses" },
  "Manchester United": { colors: "red", icon: "a red devil" },
  "Newcastle United": { colors: "black and white stripes", icon: "two seahorses" },
  "Nottingham Forest": { colors: "red", icon: "a tree" },
  "Sunderland": { colors: "red and white stripes", icon: "a ship and a lion" },
  "Tottenham Hotspur": { colors: "navy blue and white", icon: "a cockerel standing on a ball" },
  "Real Madrid": { colors: "white", icon: "a crown" },
  "FC Barcelona": { colors: "blue and garnet", icon: "a cross and stripes" },
  "Atlético Madrid": { colors: "red and white stripes", icon: "a bear and a tree" },
  "Athletic Bilbao": { colors: "red and white stripes", icon: "a tree and two wolves" },
  "Villarreal CF": { colors: "yellow", icon: "nicknamed 'The Yellow Submarine'" },
  "Real Betis": { colors: "green and white stripes", icon: "a castle motif" },
  "Celta Vigo": { colors: "sky blue", icon: "a cross" },
  "Real Sociedad": { colors: "blue and white", icon: "intertwined letters" },
  "Rayo Vallecano": { colors: "white with a red sash", icon: "a diagonal red stripe" },
  "CA Osasuna": { colors: "red", icon: "an oak leaf motif" },
  "Sevilla FC": { colors: "white", icon: "a shield with a saint's image" },
  "Getafe CF": { colors: "navy blue", icon: "a simple city crest" },
  "Deportivo Alavés": { colors: "blue and white", icon: "a black eagle" },
  "RCD Espanyol": { colors: "blue and white striped", icon: "a red and yellow diagonal stripe" },
  "Valencia CF": { colors: "orange, white and black", icon: "a bat above a shield" },
  "Levante UD": { colors: "dark blue", icon: "a shield with a star" },
  "Elche CF": { colors: "green and white", icon: "a palm tree" },
  "Racing Santander": { colors: "green and white stripes", icon: "a simple shield" },
  "Deportivo La Coruña": { colors: "blue and white", icon: "a tower" },

  // Bundesliga
  "Bayern Munich": { colors: "red and white", icon: "a shield with the Bavaria diamond pattern" },
  "Bayer Leverkusen": { colors: "red and black", icon: "a shield inside a red circle" },
  "Borussia Dortmund": { colors: "yellow and black", icon: "a ball inside a shield with the club initials" },
  "RB Leipzig": { colors: "red and white", icon: "a red bull's head" },
  "Eintracht Frankfurt": { colors: "black and red", icon: "an eagle" },
  "SC Freiburg": { colors: "red and black", icon: "a shield with the city's crest colors" },
  "VfB Stuttgart": { colors: "white and red", icon: "two antlers" },
  "SC Paderborn": { colors: "blue", icon: "a simple shield with the club initials" },

  // Serie A
  "Inter Milan": { colors: "blue and black stripes", icon: "the letters 'FCIM' in a circular crest" },
  "Napoli": { colors: "sky blue", icon: "a stylised skyline crest" },
  "AC Milan": { colors: "red and black stripes", icon: "a red cross on white" },
  "Juventus": { colors: "black and white stripes", icon: "a simplified stylised 'J'" },
  "AS Roma": { colors: "maroon and orange", icon: "a wolf" },
  "Atalanta": { colors: "blue and black", icon: "a black eagle" },
  "Bologna": { colors: "red and blue", icon: "a shield with the city's initial" },
  "Fiorentina": { colors: "purple", icon: "a fleur-de-lis" },
  "Lazio": { colors: "sky blue", icon: "an eagle" },
  "Torino": { colors: "maroon", icon: "a bull" },
  "Udinese": { colors: "black and white stripes", icon: "a stylised zebra pattern" },
  "Genoa": { colors: "red and blue", icon: "a griffin holding a shield with a cross" },
  "Cagliari": { colors: "red and blue", icon: "four Moors' heads" },
  "Parma": { colors: "yellow and blue", icon: "a cross on a shield" },
  "Lecce": { colors: "yellow and red", icon: "a she-wolf beneath an olive tree" },
  "Sassuolo": { colors: "black and green", icon: "a simple shield with a checkered pattern" },

  // Ligue 1
  "Paris Saint-Germain": { colors: "navy blue and red", icon: "the Eiffel Tower" },
  "Marseille": { colors: "white and sky blue", icon: "an Olympic flame" },
  "Monaco": { colors: "red and white", icon: "a shield with a diagonal red-and-white pattern" },
  "Lille": { colors: "red", icon: "a stylised letters 'LOSC'" },
  "Lyon": { colors: "white, blue and red", icon: "a lion" },
  "Nice": { colors: "red and black", icon: "an eagle with the city's shield" },
  "RC Lens": { colors: "red and yellow", icon: "a stylised 'RC' monogram" },
  "Strasbourg": { colors: "blue and white", icon: "a shield with a stork" },
  "Toulouse": { colors: "violet", icon: "a Occitan cross" },
  "Stade Brestois": { colors: "red and white", icon: "a shield with the city's ship motif" },
  "AJ Auxerre": { colors: "white and blue", icon: "a shield with the club initials" },

  // Liga Portugal
  "Sporting CP": { colors: "green and white", icon: "a lion" },
  "SL Benfica": { colors: "red", icon: "an eagle inside a shield" },
  "FC Porto": { colors: "blue and white stripes", icon: "a dragon" },
  "SC Braga": { colors: "red", icon: "a shield with a fortress motif" },

  // Saudi Pro League
  "Al-Nassr": { colors: "yellow", icon: "a shield with an eagle" },
  "Al-Hilal": { colors: "blue", icon: "a crescent moon" },
  "Al-Ittihad": { colors: "black, yellow and white", icon: "a shield with an eagle" },
  "Al-Ahli": { colors: "green", icon: "a shield with a palm tree motif" },

  // Additional Bundesliga and Ligue 1 / Serie A clubs
  "Borussia Mönchengladbach": { colors: "black and white", icon: "a black diamond shape (the 'Borussia-Raute') with a stylised letter B" },
  "Schalke 04": { colors: "royal blue and white", icon: "a circular crest with an 'S04' monogram" },
  "Mainz 05": { colors: "red", icon: "a shield featuring the city's wheel emblem and the number '05'" },
  "FC Augsburg": { colors: "red, white and green", icon: "a shield modeled on the city of Augsburg's coat of arms" },
  "Werder Bremen": { colors: "green and white", icon: "a white letter 'W' inside a green diamond" },
  "Rennes": { colors: "red and black", icon: "a red and black shield with the club's initials" },
  "Monza": { colors: "red and white", icon: "a shield featuring a crown, referencing the city's historic Iron Crown" },
};
