export type Difficulty = "easy" | "medium" | "hard";

export interface TriviaQuestion {
  question: string;
  options: string[];
  correctIndex: number;
  category: string;
  difficulty: Difficulty;
}

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  { question: "Which country has won the most World Cup titles?", options: ["Germany", "Italy", "Brazil", "Argentina"], correctIndex: 2, category: "World Cup", difficulty: "easy" },
  { question: "Which country won the first World Cup in 1930?", options: ["Brazil", "Uruguay", "Italy", "Argentina"], correctIndex: 1, category: "World Cup", difficulty: "medium" },
  { question: "Who won the 2026 FIFA World Cup?", options: ["Argentina", "France", "Spain", "England"], correctIndex: 2, category: "World Cup", difficulty: "easy" },
  { question: "Who won the 2022 FIFA World Cup in Qatar?", options: ["France", "Argentina", "Brazil", "Croatia"], correctIndex: 1, category: "World Cup", difficulty: "easy" },
  { question: "Which country hosted the 2018 World Cup?", options: ["Germany", "Brazil", "Russia", "Qatar"], correctIndex: 2, category: "World Cup", difficulty: "medium" },
  { question: "Which three countries co-hosted the 2026 World Cup?", options: ["Spain, Portugal, Morocco", "USA, Mexico, Canada", "Brazil, Argentina, Uruguay", "England, Scotland, Wales"], correctIndex: 1, category: "World Cup", difficulty: "easy" },
  { question: "Who scored a hat-trick in the 2022 World Cup final?", options: ["Lionel Messi", "Kylian Mbappé", "Ángel Di María", "Olivier Giroud"], correctIndex: 1, category: "World Cup", difficulty: "medium" },
  { question: "Who holds the record for most World Cup goals scored all-time?", options: ["Pelé", "Ronaldo Nazário", "Miroslav Klose", "Just Fontaine"], correctIndex: 2, category: "World Cup", difficulty: "hard" },
  { question: "In what year did England win their only World Cup?", options: ["1966", "1970", "1982", "1990"], correctIndex: 0, category: "World Cup", difficulty: "medium" },
  { question: "Which countries will jointly host the 2030 World Cup?", options: ["USA, Mexico, Canada", "Spain, Portugal, Morocco", "Germany, France, Belgium", "Japan, South Korea, China"], correctIndex: 1, category: "World Cup", difficulty: "medium" },
  { question: "Who won the Golden Boot at the 2022 World Cup?", options: ["Lionel Messi", "Kylian Mbappé", "Olivier Giroud", "Julián Álvarez"], correctIndex: 1, category: "World Cup", difficulty: "hard" },
  { question: "Which team lost the 2014 World Cup final to Germany?", options: ["Brazil", "Argentina", "Netherlands", "Colombia"], correctIndex: 1, category: "World Cup", difficulty: "medium" },
  { question: "How many teams competed in the 2026 World Cup?", options: ["32", "40", "48", "64"], correctIndex: 2, category: "World Cup", difficulty: "medium" },
  { question: "Which country hosted the 2014 World Cup?", options: ["Brazil", "South Africa", "Russia", "Chile"], correctIndex: 0, category: "World Cup", difficulty: "easy" },
  { question: "Who won the 2010 World Cup, held in South Africa?", options: ["Netherlands", "Spain", "Germany", "Uruguay"], correctIndex: 1, category: "World Cup", difficulty: "medium" },
  { question: "In what year was the Premier League founded?", options: ["1988", "1992", "1995", "2000"], correctIndex: 1, category: "Premier League", difficulty: "easy" },
  { question: "Which club has won the most Premier League titles?", options: ["Arsenal", "Chelsea", "Manchester United", "Liverpool"], correctIndex: 2, category: "Premier League", difficulty: "easy" },
  { question: "Which club went unbeaten through an entire Premier League season in 2003-04?", options: ["Chelsea", "Arsenal", "Manchester United", "Liverpool"], correctIndex: 1, category: "Premier League", difficulty: "medium" },
  { question: "Who is the Premier League's all-time top scorer?", options: ["Wayne Rooney", "Alan Shearer", "Harry Kane", "Thierry Henry"], correctIndex: 1, category: "Premier League", difficulty: "medium" },
  { question: "Which club won the first-ever Premier League title in 1992-93?", options: ["Arsenal", "Manchester United", "Blackburn Rovers", "Leeds United"], correctIndex: 1, category: "Premier League", difficulty: "hard" },
  { question: "Which manager has won the most Premier League titles?", options: ["Arsène Wenger", "Pep Guardiola", "Sir Alex Ferguson", "José Mourinho"], correctIndex: 2, category: "Premier League", difficulty: "medium" },
  { question: "Which club was relegated from the Premier League alongside Burnley and Wolves at the end of 2025-26?", options: ["West Ham", "Everton", "Leicester City", "Southampton"], correctIndex: 0, category: "Premier League", difficulty: "hard" },
  { question: "Which clubs were promoted to the Premier League for the 2026-27 season?", options: ["Leeds, Burnley, Sunderland", "Coventry, Ipswich, Hull", "Norwich, Watford, Stoke", "Luton, Southampton, Leicester"], correctIndex: 1, category: "Premier League", difficulty: "hard" },
  { question: "Which stadium has the largest capacity in the Premier League?", options: ["Emirates Stadium", "Anfield", "Old Trafford", "Tottenham Hotspur Stadium"], correctIndex: 2, category: "Premier League", difficulty: "medium" },
  { question: "Which club is nicknamed 'The Gunners'?", options: ["Chelsea", "Arsenal", "Tottenham", "West Ham"], correctIndex: 1, category: "Premier League", difficulty: "easy" },
  { question: "Which club plays home matches at Anfield?", options: ["Everton", "Liverpool", "Manchester City", "Newcastle"], correctIndex: 1, category: "Premier League", difficulty: "easy" },
  { question: "Which London club plays at Stamford Bridge?", options: ["Arsenal", "Tottenham", "Chelsea", "Fulham"], correctIndex: 2, category: "Premier League", difficulty: "easy" },
  { question: "Which Merseyside club is nicknamed 'The Reds'?", options: ["Everton", "Liverpool", "Sunderland", "Middlesbrough"], correctIndex: 1, category: "Premier League", difficulty: "easy" },
  { question: "What color are Manchester City's home shirts?", options: ["Red", "Sky blue", "White", "Claret"], correctIndex: 1, category: "Premier League", difficulty: "easy" },
  { question: "Which club is nicknamed 'The Red Devils'?", options: ["Liverpool", "Manchester United", "Nottingham Forest", "Sheffield United"], correctIndex: 1, category: "Premier League", difficulty: "easy" },
  { question: "Which club has won the most European Cup/Champions League titles?", options: ["AC Milan", "Liverpool", "Real Madrid", "Bayern Munich"], correctIndex: 2, category: "Champions League", difficulty: "easy" },
  { question: "What was the Champions League called before its 1992 rebrand?", options: ["European Cup", "UEFA Cup", "European Super League", "Continental Cup"], correctIndex: 0, category: "Champions League", difficulty: "medium" },
  { question: "Which English club won an all-English Champions League final in 2019?", options: ["Manchester City", "Chelsea", "Liverpool", "Manchester United"], correctIndex: 2, category: "Champions League", difficulty: "medium" },
  { question: "Which two English clubs met in the 2021 Champions League final?", options: ["Liverpool and Chelsea", "Chelsea and Manchester City", "Manchester City and Liverpool", "Arsenal and Chelsea"], correctIndex: 1, category: "Champions League", difficulty: "hard" },
  { question: "Which club completed a historic treble in 1999 with a dramatic late final comeback?", options: ["Manchester United", "Arsenal", "Bayern Munich", "Juventus"], correctIndex: 0, category: "Champions League", difficulty: "medium" },
  { question: "Which country's top division is Serie A?", options: ["Spain", "Italy", "Portugal", "France"], correctIndex: 1, category: "European Football", difficulty: "easy" },
  { question: "Which European club competition sits one tier below the Champions League?", options: ["Conference League", "Europa League", "Super Cup", "Community Shield"], correctIndex: 1, category: "Champions League", difficulty: "medium" },
  { question: "Which club is nicknamed 'Los Blancos'?", options: ["Barcelona", "Atlético Madrid", "Real Madrid", "Valencia"], correctIndex: 2, category: "European Football", difficulty: "medium" },
  { question: "Which Spanish club plays home matches at Camp Nou?", options: ["Real Madrid", "Barcelona", "Sevilla", "Atlético Madrid"], correctIndex: 1, category: "European Football", difficulty: "easy" },
  { question: "Which German club has won the most Bundesliga titles?", options: ["Borussia Dortmund", "Bayer Leverkusen", "Bayern Munich", "RB Leipzig"], correctIndex: 2, category: "European Football", difficulty: "medium" },
  { question: "Who has won the most Ballon d'Or awards?", options: ["Cristiano Ronaldo", "Lionel Messi", "Michel Platini", "Johan Cruyff"], correctIndex: 1, category: "Legends", difficulty: "easy" },
  { question: "Which player holds the record for most international goals in men's football?", options: ["Lionel Messi", "Pelé", "Cristiano Ronaldo", "Romelu Lukaku"], correctIndex: 2, category: "Legends", difficulty: "medium" },
  { question: "Which player is nicknamed 'The Egyptian King'?", options: ["Mohamed Salah", "Sadio Mané", "Riyad Mahrez", "Amr Warda"], correctIndex: 0, category: "Legends", difficulty: "easy" },
  { question: "Which club did Lionel Messi join after leaving Barcelona in 2021?", options: ["Inter Miami", "Paris Saint-Germain", "Manchester City", "Al-Hilal"], correctIndex: 1, category: "Legends", difficulty: "medium" },
  { question: "Which player scored the infamous 'Hand of God' goal in 1986?", options: ["Pelé", "Diego Maradona", "Gary Lineker", "Michel Platini"], correctIndex: 1, category: "Legends", difficulty: "medium" },
  { question: "Which country does Erling Haaland represent internationally?", options: ["Sweden", "Denmark", "Norway", "Iceland"], correctIndex: 2, category: "Legends", difficulty: "easy" },
  { question: "Which club has Erling Haaland played for since 2022?", options: ["Borussia Dortmund", "Manchester City", "Real Madrid", "Bayern Munich"], correctIndex: 1, category: "Legends", difficulty: "easy" },
  { question: "Which player is widely known by the nickname 'CR7'?", options: ["Cristiano Ronaldo", "Ronaldinho", "Ronaldo Nazário", "Carlos Tevez"], correctIndex: 0, category: "Legends", difficulty: "easy" },
  { question: "Which Brazilian legend won three World Cups as a player (1958, 1962, 1970)?", options: ["Ronaldinho", "Pelé", "Zico", "Ronaldo Nazário"], correctIndex: 1, category: "Legends", difficulty: "medium" },
  { question: "Who has scored the most goals in Champions League history?", options: ["Lionel Messi", "Robert Lewandowski", "Cristiano Ronaldo", "Karim Benzema"], correctIndex: 2, category: "Legends", difficulty: "medium" },
  { question: "How many players does each team have on the pitch, including the goalkeeper?", options: ["9", "10", "11", "12"], correctIndex: 2, category: "Rules", difficulty: "easy" },
  { question: "How long is a standard football match, excluding stoppage time?", options: ["60 minutes", "80 minutes", "90 minutes", "120 minutes"], correctIndex: 2, category: "Rules", difficulty: "easy" },
  { question: "What is awarded for a foul committed inside the penalty area?", options: ["A free kick", "A penalty kick", "A corner kick", "A yellow card only"], correctIndex: 1, category: "Rules", difficulty: "easy" },
  { question: "What color card results in a player being sent off?", options: ["Yellow", "Orange", "Red", "Blue"], correctIndex: 2, category: "Rules", difficulty: "easy" },
  { question: "What does VAR stand for?", options: ["Video Assistant Referee", "Virtual Action Replay", "Video Analysis Report", "Visual Aid Review"], correctIndex: 0, category: "Rules", difficulty: "easy" },
  { question: "How many yellow cards in one match result in an automatic red card?", options: ["1", "2", "3", "It doesn't happen"], correctIndex: 1, category: "Rules", difficulty: "easy" },
  { question: "What is the total duration of extra time in a knockout match?", options: ["15 minutes", "20 minutes", "30 minutes", "45 minutes"], correctIndex: 2, category: "Rules", difficulty: "medium" },
  { question: "What is it called when a player scores three goals in one match?", options: ["A brace", "A hat-trick", "A treble", "A triple"], correctIndex: 1, category: "Rules", difficulty: "easy" },
  { question: "What is a 'clean sheet'?", options: ["A match with no fouls", "A match where a team doesn't concede", "A perfect pass completion rate", "A new kit design"], correctIndex: 1, category: "Rules", difficulty: "easy" },
  { question: "Which formation uses four defenders, three midfielders, and three forwards?", options: ["4-4-2", "4-3-3", "3-5-2", "5-3-2"], correctIndex: 1, category: "Rules", difficulty: "medium" },
  { question: "What is a 'loan deal' in football?", options: ["A permanent transfer", "A temporary move to another club", "A free transfer", "A youth academy signing"], correctIndex: 1, category: "Transfers", difficulty: "easy" },
  { question: "What typically happens on 'deadline day'?", options: ["The season starts", "The transfer window closes", "Awards are given out", "Fixtures are announced"], correctIndex: 1, category: "Transfers", difficulty: "easy" },
  { question: "What is a 'release clause'?", options: ["A rule about substitutions", "A pre-agreed fee that guarantees a sale if met", "A type of injury clause", "A stadium naming rights deal"], correctIndex: 1, category: "Transfers", difficulty: "medium" },
  { question: "When does the Premier League's summer transfer window typically close?", options: ["Mid-July", "Early September", "End of October", "Christmas"], correctIndex: 1, category: "Transfers", difficulty: "medium" },
  { question: "What is it called when a player joins a new club for free after their contract expires?", options: ["Loan move", "Free transfer", "Swap deal", "Release fee"], correctIndex: 1, category: "Transfers", difficulty: "easy" },
  { question: "Which club broke the world transfer record by signing Neymar in 2017?", options: ["Real Madrid", "Manchester City", "Paris Saint-Germain", "Barcelona"], correctIndex: 2, category: "Transfers", difficulty: "medium" },
  { question: "Neymar's 2017 transfer fee was reported at roughly how much?", options: ["€100 million", "€150 million", "€222 million", "€300 million"], correctIndex: 2, category: "Transfers", difficulty: "hard" },
  { question: "What is the term for a player who has played for their national team?", options: ["A starter", "A capped player", "A veteran", "A draftee"], correctIndex: 1, category: "Transfers", difficulty: "medium" },
  { question: "What is a 'buyback clause'?", options: ["A fine for missing training", "The right for a selling club to re-sign a player later", "A bonus for scoring goals", "A relegation penalty"], correctIndex: 1, category: "Transfers", difficulty: "medium" },
  { question: "Deadline day is typically known for what kind of activity?", options: ["Quiet, no news", "A flurry of last-minute deals", "Only youth signings", "Retirement announcements"], correctIndex: 1, category: "Transfers", difficulty: "easy" },
  { question: "Which player is affectionately nicknamed 'The Flea' due to his small stature and dribbling style?", options: ["Sergio Agüero", "Lionel Messi", "Neymar", "Ángel Di María"], correctIndex: 1, category: "Legends", difficulty: "easy" },
  { question: "Which England legend is famous for his precisely bent free kicks and global off-pitch fame?", options: ["Frank Lampard", "Steven Gerrard", "David Beckham", "Paul Scholes"], correctIndex: 2, category: "Legends", difficulty: "easy" },
  { question: "Which Uruguayan striker's career is known for both his goalscoring and on-pitch biting incidents?", options: ["Edinson Cavani", "Luis Suárez", "Diego Forlán", "Darwin Núñez"], correctIndex: 1, category: "Legends", difficulty: "medium" },
  { question: "Which player won the 2026 World Cup Golden Boot, becoming the first man to win it twice?", options: ["Lionel Messi", "Erling Haaland", "Kylian Mbappé", "Harry Kane"], correctIndex: 2, category: "World Cup", difficulty: "medium" },
  { question: "Who was named the 2026 World Cup's best player, winning the Golden Ball?", options: ["Rodri", "Lamine Yamal", "Kylian Mbappé", "Pedri"], correctIndex: 0, category: "World Cup", difficulty: "hard" },
  { question: "Which country's men's team has never won a World Cup despite reaching the final three times, including 1974, 1978, and 2010?", options: ["Netherlands", "Sweden", "Hungary", "Portugal"], correctIndex: 0, category: "World Cup", difficulty: "medium" },
  { question: "Which Welsh player became the world's most expensive footballer in 2013, moving from Tottenham to Real Madrid?", options: ["Aaron Ramsey", "Gareth Bale", "Ryan Giggs", "Ashley Williams"], correctIndex: 1, category: "Transfers", difficulty: "medium" },
  { question: "What is the maximum squad size permitted at a FIFA World Cup finals tournament, as used at the 2022 and 2026 editions?", options: ["23", "25", "26", "28"], correctIndex: 2, category: "Rules", difficulty: "medium" },
  { question: "Manchester City's 2022-23 treble under Pep Guardiola included the Premier League, FA Cup, and which European trophy?", options: ["Europa League", "UEFA Champions League", "UEFA Super Cup", "Europa Conference League"], correctIndex: 1, category: "Champions League", difficulty: "easy" },
];
